env:
  http-port: 8180

allowed-origins:
  - "*"

cf-turnstile: ""

cf-r2:
  judge-data:
    url: ""
    token: ""
    key: ""
    secret: ""
  didapipa-oj:
    url: ""
    token: ""
    key: ""
    secret: ""

r2-url: ""

email:
  email: ""
  password: ""
  host: ""
  port: 587

template:
  hdu: "resource/template/hdu.md"

judge-data-max-size: 33554432
