judger: test

go-judge-url: ""

#同时评测的job数
max-job: 2
max-job-remote: 10
max-job-run: 1
max-job-bot: 1

judge-data:
  url: ""
  token: ""
  key: ""
  secret: ""

files:
  ts-env: ""
  testlib: ""
  bot-judge: ""
